sudo: required

language: python

python:
    - "2.7"

install:
    - pip install -r requirements.txt

services:
    - docker

before_install:
    - docker run --name postgres -d -e POSTGRES_PASSWORD=postgres -e POSTGRES_USER=postgres -e POSTGRES_DB=logs postgres:9.4

script:
     - nosetests --with-coverage
     - ./extract/parse_downloads.py data/110302-sample && mv data/110302-sample.csv data/all.log.csv && docker run --link postgres:postgres --rm -e PGPASSWORD=postgres --volume $PWD/sql:/sql --volume $PWD/data:/data postgres:9.4 psql --dbname=logs --host=postgres --username=postgres -v ON_ERROR_STOP=1 -f /sql/build_database.sql && docker run --link postgres:postgres --rm -e PGPASSWORD=postgres --volume $PWD/sql:/sql --volume $PWD/data:/data postgres:9.4 psql --dbname=logs --host=postgres --username=postgres -v ON_ERROR_STOP=1 -f /sql/tests.sql

after_success:
  - coveralls